//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.17 at 05:45:19 PM CEST 
//


package com.github.digitalheir.simple;

import com.github.digitalheir.unicode.Character;
import com.github.digitalheir.unicode.Entitygroups;
import com.github.digitalheir.unicode.Mathvariants;

import java.util.List;

public class Charlist {

    public final Entitygroups entitygroups;
    public final Mathvariants mathvariants;
    public final List<UnicodeCharacter> character;

    public Charlist(Entitygroups entitygroups, Mathvariants mathvariants, List<UnicodeCharacter> character) {
        this.entitygroups = entitygroups;
        this.mathvariants = mathvariants;
        this.character = character;
    }
}