//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.17 at 05:45:19 PM CEST 
//


package com.github.digitalheir.unicode;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entitygroups",
    "mathvariants",
    "character"
})
@XmlRootElement(name = "charlist")
public class Charlist {

    public Entitygroups entitygroups;
    public Mathvariants mathvariants;
    public List<Character> character;

    /**
     * Gets the value of the entitygroups property.
     * 
     * @return
     *     possible object is
     *     {@link Entitygroups }
     *     
     */
    public Entitygroups getEntitygroups() {
        return entitygroups;
    }

    /**
     * Sets the value of the entitygroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entitygroups }
     *     
     */
    public void setEntitygroups(Entitygroups value) {
        this.entitygroups = value;
    }

    /**
     * Gets the value of the mathvariants property.
     * 
     * @return
     *     possible object is
     *     {@link Mathvariants }
     *     
     */
    public Mathvariants getMathvariants() {
        return mathvariants;
    }

    /**
     * Sets the value of the mathvariants property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mathvariants }
     *     
     */
    public void setMathvariants(Mathvariants value) {
        this.mathvariants = value;
    }

    /**
     * Gets the value of the character property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the character property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCharacter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Character }
     * 
     * 
     */
    public List<Character> getCharacter() {
        if (character == null) {
            character = new ArrayList<Character>();
        }
        return this.character;
    }

}
