//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.17 at 05:45:19 PM CEST 
//


package com.github.digitalheir.unicode;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "desc",
    "elsrender"
})
@XmlRootElement(name = "Elsevier")
public class Elsevier {

    @XmlAttribute(name = "grid", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String grid;
    @XmlAttribute(name = "ent")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ent;
    protected String desc;
    protected String elsrender;

    /**
     * Gets the value of the grid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrid() {
        return grid;
    }

    /**
     * Sets the value of the grid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrid(String value) {
        this.grid = value;
    }

    /**
     * Gets the value of the ent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnt() {
        if (ent == null) {
            return "";
        } else {
            return ent;
        }
    }

    /**
     * Sets the value of the ent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnt(String value) {
        this.ent = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the elsrender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElsrender() {
        return elsrender;
    }

    /**
     * Sets the value of the elsrender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElsrender(String value) {
        this.elsrender = value;
    }

}
