//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.17 at 05:45:19 PM CEST 
//


package com.github.digitalheir.unicode;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.digitalheir package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.digitalheir
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Bmp }
     * 
     */
    public Bmp createBmp() {
        return new Bmp();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Character }
     * 
     */
    public Character createCharacter() {
        return new Character();
    }

    /**
     * Create an instance of {@link Elsevier }
     * 
     */
    public Elsevier createElsevier() {
        return new Elsevier();
    }

    /**
     * Create an instance of {@link Wolfram }
     * 
     */
    public Wolfram createWolfram() {
        return new Wolfram();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link Font }
     * 
     */
    public Font createFont() {
        return new Font();
    }

    /**
     * Create an instance of {@link Surrogate }
     * 
     */
    public Surrogate createSurrogate() {
        return new Surrogate();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Set }
     * 
     */
    public Set createSet() {
        return new Set();
    }

    /**
     * Create an instance of {@link Charlist }
     * 
     */
    public Charlist createCharlist() {
        return new Charlist();
    }

    /**
     * Create an instance of {@link Entitygroups }
     * 
     */
    public Entitygroups createEntitygroups() {
        return new Entitygroups();
    }

    /**
     * Create an instance of {@link Mathvariants }
     * 
     */
    public Mathvariants createMathvariants() {
        return new Mathvariants();
    }

    /**
     * Create an instance of {@link Mathvariant }
     * 
     */
    public Mathvariant createMathvariant() {
        return new Mathvariant();
    }

}
